### PR TITLE
Add a new module to replace all the '$' subsetting operators with '[[' in the current buffer

### PR DESCRIPTION
**Pull request by PMassicotte**
This PR add a new module to replace all the `$` subsetting operators with `[[` in the current buffer.  The new keybinding is `<localleader>cs` (change subsetting).

This works with any number of nested subset:

```r
x$a

x$a$b$c$d
```

Will become:

```r
x[["a"]]

x[["a"]][["b"]][["c"]][["d"]]
```

I also created a new folder named `format` that includes all the new lua modules dedicated to format R code to comply with the `lintr` package.

### CODE REVIEW

**Comment by jalvesaq** [comment]
Great job! The only thing missing is the documentation.

**Comment by PMassicotte** [comment]
oups! will do that!

**Comment by PMassicotte** [comment]
To make sure I do things correctly for the documentation. Should I modify directly the `R.nvim.txt` by adding a new section?

**Comment by jalvesaq** [comment]
> To make sure I do things correctly for the documentation. Should I modify directly the R.nvim.txt by adding a new section?

Yes, we have no other similar feature. So, its documentation would be in a new section.

**Comment by jalvesaq** [comment]
Opss. I thought that this was about installing packages...

**Comment by PMassicotte** [comment]
Was asking because I was wondering if this file was automatically generated based on function headers (likr using roxygen).

**Comment by jalvesaq** [comment]
I think that section 6.36. can have a general title to accommodate both "Converting numbers to explicit integers" and "Replace subsetting operators".

**Comment by PMassicotte** [comment]
I modified the help section. Let me know if you think it needs more improvement.

**Comment by jalvesaq** [comment]
It's good! Thanks!

**Pull request merged**
