### PR TITLE
Optimize completion infrastructure for Lua

### PR DESCRIPTION
**Pull request by jalvesaq**
- Sanitize strings for Lua evaluation:
  - Replace `\` with \x12
  - Replace `'` with \x13
  - Replace `\n` with \x14
- Move functions shared by nvimcom.c and rnvimserver.c to common.c.
- Remove outdated information from documentation.

### CODE REVIEW

**Comment by jalvesaq** [comment]
This pull request changes the code originally developed for omni-completion and optimizes it to interact with the Lua code. The main goal is to make it easier to eventually convert `rnvimserver` into a C library for Lua. To test this pull request, please, use it along with the branch [optimized](https://github.com/R-nvim/cmp-r/tree/optimized) of `cmp-r`.

Part of `cmp-r` code was converted to C and incorporated into `R.nvim`.

**Comment by PMassicotte** [comment]
Using 

```lua
        "R-nvim/R.nvim",
        commit = "c0c167eddadb6b8aa41cea5f225c202d6aeac83d",
```

and 

```lua
return {
    "R-nvim/cmp-r",
    branch = "optimized",
    config = function()
        require("cmp_r").setup({
            filetypes = { "r", "rmd", "quarto" },
            doc_width = 150,
        })
    end,
}
````

I am getting error when auto complete is triggered: 

image

**Comment by jalvesaq** [comment]
I added a commit to `cmp-r` postponing the definition of send_to_nvimcom. It should work now.

**Comment by PMassicotte** [comment]
I am now getting this:

image

**Comment by PMassicotte** [comment]
It seems to work if I use it in a 1 liner like

```r
lm()
```

But not on a piped expression.

**Comment by jalvesaq** [comment]
Thanks! I can replicate the bug here. I will see what's happening.

**Comment by PMassicotte** [comment]
Peek 2024-03-03 07-03

**Comment by jalvesaq** [comment]
The code supposes that the `data.frame` will be in the `.GlobalEnv` environment. I didn't consider the possibility of the `data.frame` being from a package. Then, the `rnvimserver` gets a SIGINT when trying to access a NULL GlobalEnv (because no code creating an object was sent to R yet).

**Comment by PMassicotte** [comment]
> The code supposes that the `data.frame` will be in the `.GlobalEnv` environment. I didn't consider the possibility of the `data.frame` being from a package. Then, the `rnvimserver` gets a SIGINT when trying to access a NULL GlobalEnv (because no code creating an object was sent to R yet).

Good catch, if I do `df <- mtcars` it works just fine.

**Comment by PMassicotte** [comment]
And completion works fine now in `scale_x_continuous()`

image

This is fixing: https://github.com/R-nvim/cmp-r/issues/3

**Comment by jalvesaq** [comment]
It should find `data.frame`s in libraries too now.

**Comment by PMassicotte** [comment]
I am still getting the same error (connection with rnvimserver was lost)

Using:

```lua
        "R-nvim/R.nvim",
        commit = "313f6c78ae5b8057ed5933bb1e8d90d6a258d4f0",
```

If I type `:messages` I get

```bash
"Server" exited with status 139                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                
Press ENTER or type command to continue 
```

**Comment by jalvesaq** [comment]
I had forgotten to increase `nvimcom` version number to force the recompilation of the `rnvimserver`. I increased it now.

**Comment by PMassicotte** [comment]
Victory :1st_place_medal: 

All good now on my side. These are really nice changes.

**Comment by PMassicotte** [comment]
I think this can be merged. Good job!

**Comment by jalvesaq** [comment]
Are you sure? Maybe we could use it for some time. If no bugs appear, we squash and merge it.

**Comment by PMassicotte** [comment]
I am currently working on a project. I think I will do it for 2-3h. I can report back and dig up in your code change there after is I can not spot something obvious.

**Comment by jalvesaq** [comment]
Good! If you don't find bugs in the next couple of hours, we merge it.

**Comment by PMassicotte** [comment]
I just spent 2h to extensively use the completion in the project I'm working on and no issue at all. It feels snappy and responsive!

**Comment by jalvesaq** [comment]
So, we can squash and merge...

**Pull request merged**
