### PR TITLE
New feature: split file paths into its components

### PR DESCRIPTION
**Pull request by PMassicotte**
This PR adds two new keybindings:

1. `<localleader>sp`: Split a file path and wrap it around the `paste()` function.
2.  `<localleader>sh`: Split a file path and wrap it around the `here()` function.

This allows to breaks long lines to nicely format code.

Peek 2024-04-05 08-47

After, one can use the preferred formatter to wrap lines.

### CODE REVIEW

**Comment by wurli** [comment]
😮 I like this! Worth considering other features in this area, e.g. [{codegrip}](https://github.com/lionel-/codegrip)-style reshaping?

One comment, should Windows path separators `\\` also be used to split paths? Both `/` and `\\` as file separators are valid if using R on Windows so this is pretty rare, but does happen.

**Comment by PMassicotte** [comment]
> 😮 I like this! Worth considering other features in this area, e.g. [{codegrip}](https://github.com/lionel-/codegrip)-style reshaping?
> 
> One comment, should Windows path separators `\\` also be used to split paths? Both `/` and `\\` as file separators are valid if using R on Windows so this is pretty rare, but does happen.

I will check for windows support, I really hate seeing `\\` :) But you are right. As for _node_ formatting, I use  ["nvim-treesitter/nvim-treesitter"  (](https://github.com/Wansmer/treesj) which works very nicely. Could be an option here, but would introduce 1 dependency.

**Comment by jalvesaq** [comment]
Good job, @PMassicotte! I see no problem in depending on `treejs`, but its README says that it already has a preset for R. Did you improve the preset?

**Comment by PMassicotte** [comment]
`treejs` does not split path, it _simply_ reflows the code over multiple lines. At the moment, this PR do not need `treejs`, it will on only split the path. into components.

**Comment by jalvesaq** [comment]
Looking at the split path:

- "Edit" would be a better category for the split commands because in the "Command" category are the commands sent to R Console.
- The command `require('r.path').split_path()` repeats the string "path". So, maybe the function name could be `split` instead of `split_path`.
- You use treesitter... People who don't have a tree-sitter parser for R will miss interesting `R.nvim` features. Should we make the availability of a tree-sitter parser for R a required dependency?
- A short description of the split path commands could be added to the list of new features in the _Transitioning from Nvim-R_ section in the README.

**Comment by PMassicotte** [comment]
> * You use treesitter... People who don't have a tree-sitter parser for R will miss interesting `R.nvim` features. Should we make the availability of a tree-sitter parser for R a required dependency?

I think that would be nice. We have few functionalities that now relies on it.

New commit coming for your proposed changes.

**Comment by jalvesaq** [comment]
Is it ready to be merged now?

**Comment by PMassicotte** [comment]
Yes all good I think!

**Comment by jalvesaq** [comment]
Thank you!

**Pull request merged**
