### PR TITLE
Create and update the params list

### LINKED ISSUE #255: Quarto parameter evaluation in interactive session
When working with Quarto documents interactively in Rstudio it is possible to evaluate the parameters set within the Quarto YAML header during code execution.

In Rnvim these parameters are only available on preview of the quarto file. I presume this might be some custom option built into Rstudio so might not be available to Rnvim?

A working example.
In Rstudio the below example in an interactive session will be able to produce the object pc_codes containing the three snomed codes from the YAML params. In Rnvim this functionality is not replicated.

YAML Header

```
format:
  pdf:
    toc: true
    documentclass: report
    margin-left: 20mm
    margin-right: 20mm
    margin-top: 20mm
    margin-bottom: 20mm
params:
  pc_search: true
  pc_1: "267102003"
  pc_2: "421581006"
  pc_3: "40739000"
  start_date: "2023-01-01"
  end_date: "2024-08-31"
  disease: "Sore Throat"
title: "Summary data for `r params$disease` presentations from `r params$start_date` - `r params$end_date`"
author: "Jason Pott"
```
R Chunk
```{r}
pc_codes <- c(
  if(!is.null(params$pc_1)){params$pc_1},
  if(!is.null(params$pc_2)){params$pc_2},
  if(!is.null(params$pc_3)){params$pc_3}
)

```

Obviously very grateful for the time and effort put into Rnvim I use it daily and understand if this feature parity is out of scope.

### PR DESCRIPTION
**Pull request by jalvesaq**
Close #255

### CODE REVIEW

**Comment by PMassicotte** [comment]
Looks good. The only thing is that I have a message saying loading...

I have to press enter to get rid of it and get to the prompt.

image

**Comment by PMassicotte** [comment]
Also, if I close the terminal with rq and reopen it with rf, params is not loaded.

**Comment by jalvesaq** [comment]
The bugs are fixed, but you have to force the update of `nvimcom`:

```sh
echo "remove.packages('nvimcom')" | R
```

**Comment by PMassicotte** [comment]
Good job!

**Comment by jalvesaq** [comment]
Maybe it should be updated on the BufEnter event too because users might have more than one Quarto document open...

**Comment by PMassicotte** [comment]
That would make sense to load params every time. This is not something costly.

**Comment by jalvesaq** [comment]
The branch "fix_get_params" includes the BufEnter event. But I didn't made the pull request yet because I still have to fix the C stack bug on Windows.

**Pull request merged**
