### PR TITLE
Complete methods arguments

### PR DESCRIPTION
**Pull request by jalvesaq**

### CODE REVIEW

**Comment by jalvesaq** [comment]
This pull request changes the completion of functions according to the class of the first argument. If the function whose arguments are being completed is a generic one, and there is already a first argument, the class of the first argument is used to search for an appropriate method. If a method is found, the arguments returned are from the method, and not from the generic function. Example of how to see different arguments for `print()`:

```r
fctr <- factor(c("a", "b", "a", "b", "a"))
mdl <- lm(rnorm(100) ~ runif(100))
slm <- summary(mdl)
print(fctr,)
print(mdl,)
print(slm,)
print(mtcars,)
```

Note: Requires `cmp-r`'s  branch `method_compl`.

**Comment by PMassicotte** [comment]
oh great, finishing something and testing it in few minutes

**Comment by PMassicotte** [comment]
Should I get something different for `print.summary.lm`?

image

**Comment by PMassicotte** [comment]
Besides that, all other cases work just fine. Also tested `<localleader>rh` and it works. Awesome work!

**Comment by PMassicotte** [comment]
Should it also work tibble (for example)? 

image

**Comment by jalvesaq** [comment]
Did you send the code to R before trying the completions? It gets the class of objects from R's workspace.

**Comment by jalvesaq** [comment]
I added a commit to deal with `library_name::`...

**Comment by jalvesaq** [comment]
Currently, it tries to find a method for the first element from the class vector, and the function `print` has no method for `tibble`s first class, `tbl_df`; only for the second, `tbl`.

**Comment by jalvesaq** [comment]
As usual, I forgot to increase nvimcom version number. I did it now.

**Comment by PMassicotte** [comment]
Trying right now :)

**Comment by PMassicotte** [comment]
Have you pushed it?

**Comment by jalvesaq** [comment]
Yes: https://github.com/R-nvim/R.nvim/pull/77/commits/1f93afd54395ed272ce17527c5d78329155755e5

**Comment by PMassicotte** [comment]
Not sure what is going on, it is not updading on my side

image

**Comment by jalvesaq** [comment]
It has some limitations:
- Only the arguments of the selected method are included in the menu. The arguments for the generic function should be included too.
- Only rarely, does it resolve selected items and show the corresponding documentation.

**Comment by PMassicotte** [comment]
image

**Comment by jalvesaq** [comment]
Most of the changes are in R.nvim, not in cmp-r

**Comment by PMassicotte** [comment]
> Did you send the code to R before trying the completions? It gets the class of objects from R's workspace.

Yes, it is in the current env:

image

**Comment by jalvesaq** [comment]
I get this:

image

**Comment by PMassicotte** [comment]
> I get this:
> 
> image

1. Ok, not sure why it is not working on my side.
2. Still not able to update. If I click here (https://github.com/R-nvim/R.nvim/commit/1f93afd54395ed272ce17527c5d78329155755e5) it says that the commit is not associated to any branch and/or repo.

**Comment by PMassicotte** [comment]
The latest commit on R.nvim is from yesterday:

image

**Comment by jalvesaq** [comment]
I don't know how to fix the pull request. I can close this and open a new one...

**Pull request closed without merging**
