### PR TITLE
Fix some issues

### PR DESCRIPTION
**Pull request by jalvesaq**

### CODE REVIEW

**Comment by jalvesaq** [comment]
This pull request fixes minor issues when getting params:
* Update the params list when entering the buffer.
* Update the object browser after updating the params.

But, most importantly, it should avoid C stack bug on Windows when running some R.nvim commands while R is busy computing something. To try it, send to R a command that will turn it busy for some seconds making complex computations or, even better, opening a large data file. While R is busy, do commands that require R to work in the background, like `\rh`.

**Comment by jalvesaq** [comment]
Expected behavior on the "main" branch after `\rh` while R is busy:

- On Unix: R only executes in the background the command corresponding to `\rh` after finishing the top-level task.
- On Windows: stack corruption and, some commands later, R crash.

Expected behavior on the "fix_get_params" branch after `\rh` while R is busy:

- On Unix: same behavior as before.
- On Windows: the command corresponding to `\rh` is ignored, but there is no subsequent R crash.

**Review by akthe-at — APPROVED** [review]
I tested a "random data generation script" on the main branch...definitely had the expected stack corruption and crash.  After switching to this `fix_get_params` branch and running the same script, no issues, no crash. Very Nice!

This was tested on Windows 11, with R4.4.1 using the below script.

```r
# Generate and process large dataset
library(data.table)

# Set the random seed for reproducibility
set.seed(42)

# Number of rows to generate
n_rows <- 1000000

cat("Generating", n_rows, "rows of data...\n")

# Generate various types of columns
data <- data.table(
  id = 1:n_rows,
  timestamp = as.POSIXct(Sys.time()) + runif(n_rows, 0, 365*24*60*60),
  numeric_normal = rnorm(n_rows, mean = 100, sd = 15),
  numeric_uniform = runif(n_rows, 0, 1000),
  categorical = sample(LETTERS[1:5], n_rows, replace = TRUE),
  boolean = sample(c(TRUE, FALSE), n_rows, replace = TRUE),
  large_numbers = rlnorm(n_rows, meanlog = 10, sdlog = 1),
  small_decimals = runif(n_rows, 0.0001, 0.1),
  text = sapply(1:n_rows, function(x) 
    paste0(sample(c(LETTERS, letters), 
                 size = sample(5:20, 1), 
                 replace = TRUE), 
           collapse = ""))
)

# Add some calculated columns
data[, `:=`(
  scaled_normal = scale(numeric_normal),
  log_large = log(large_numbers),
  category_count = .N, 
  by = categorical
)]

cat("Writing data to CSV...\n")
start_time <- Sys.time()

# Write to CSV using data.table's fast writer
fwrite(data, "large_dataset.csv")

write_time <- difftime(Sys.time(), start_time, units = "secs")
cat(sprintf("Write time: %.2f seconds\n", write_time))

# Get file size
file_size <- file.size("large_dataset.csv") / (1024^2)  # Convert to MB
cat(sprintf("File size: %.2f MB\n", file_size))

cat("Reading data back from CSV...\n")
start_time <- Sys.time()

# Read the data back
data_read <- fread("large_dataset.csv")

read_time <- difftime(Sys.time(), start_time, units = "secs")
cat(sprintf("Read time: %.2f seconds\n", read_time))

# Verify data integrity
cat("\nVerifying data integrity:\n")
cat("Original dimensions:", dim(data), "\n")
cat("Read dimensions:", dim(data_read), "\n")

# Basic summary
cat("\nQuick summary of numeric columns:\n")
print(summary(data_read[, .(numeric_normal, numeric_uniform, large_numbers)]))

# Memory usage
cat("\nMemory usage:\n")
print(object.size(data_read), units = "MB")
```

**Comment by jalvesaq** [comment]
Thanks for the test, @akthe-at!

I'm almost sure that the bug reported by @jasonpott was not fixed: R crashes when updating the `params` list.

**Comment by akthe-at** [comment]
@jalvesaq I apologize, I missed all of the quarto related stuff and the actual issue that was filed. I see it now, and I just went and tested the minimal example that @jasonpott provided. 
I am getting very mixed results now:
## When Using Nushell on Windows
After saving, closing and reopening this buffer I also get a C Stack error for that .qmd file, and I also get Rnvimcom closing with status 5 and get even get the C stack error to occur and rnvimcom won't even restart until I start a new shell session.

## When using Git bash on Windows
I do not get any errors, I just am not able to read the params object, but no crashes or errors...that is what I normally would experience in the past.

## Powershell Core on windows
Rnvimcom crashes right away with status 1 when I tried to start it up...

## Regular Windows Powershell
Reacts just like Git bash did above.

**Comment by jalvesaq** [comment]
Thank you, @akthe-at ! Can you try again? Now, the command creating the `params` list is sent to the R Console, thus avoiding messing with R memory.

**Comment by akthe-at** [comment]
Close! 
{04470FA9-8153-4382-BD22-199CAE37479D}

**Comment by akthe-at** [comment]
Just needs a boolean conversion from yamls lowercase to R

**Comment by jalvesaq** [comment]
We have to convert `true` and `false`. The `params` variable is meant to be translated by `knitr` when weaving the document, but we are imitating RStudio behavior, which makes an R list available in `.GlobalEnv`.

**Comment by jalvesaq** [comment]
It should work now. I tested it with:

```yaml
params:
    a1: 0.8
    a2: ["abcd", "defg"]
    a3: false
    a4: true
    a5: [123, "hijk"]
```

Of course in my test the condition was `config.is_windows == false`.

**Comment by jalvesaq** [comment]
I almost forgot to test with `radian`... Support for `bracketed_paste` is still missing. I will add it.

**Comment by jalvesaq** [comment]
Merged now. Thank you!

**Pull request merged**
