### PR TITLE
Fix RFormat for entire file

### PR DESCRIPTION
**Pull request by jalvesaq**

### CODE REVIEW

**Comment by jalvesaq** [comment]
This fixes `:RFormat` when applied to the entire file, but it only works if using the `styler` package, not `formatR`. It seems that `formatR` can't deal with non-R files such as Quarto documents. Perhaps we should drop the option of using `formatR` and only use `styler`.

**Comment by jalvesaq** [comment]
I removed the integration with the `formatR` package. The pull request is ready to be either squashed and merged  (if we want to keep the `:RFormat` command) or closed (if we expect that other plugins are used for that).

**Comment by PMassicotte** [comment]
Good question. I think we can merge this and refactor/deprecate later if necessary. What do you think?

**Comment by jalvesaq** [comment]
> Good question. I think we can merge this and refactor/deprecate later if necessary. What do you think?

I agree.

**Pull request merged**
